package bookingdr;

import javax.swing.table.DefaultTableModel;
import model.modelBooking;
import model.modelMahasiswa;
import model.modelRuangan;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vitky
 */

public class BookingDiscussionRoom extends javax.swing.JFrame {
    /**
     * Creates new form BookingDiscussionRoom
     */
    public BookingDiscussionRoom() {
        initComponents();
    }
    
    
    public void BookingDiscussionRooms(){        
        modelBooking modelB =  new modelBooking();        
        modelB.modelBooking(menuPemesanan, halamanMahasiswa, halamanRuangan, halamanBooking);
        modelB.setRuanganBookingCB(RuanganBooking);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        halamanMahasiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NIM = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Jurusan = new javax.swing.JTextField();
        tambahMahasiswa = new javax.swing.JButton();
        updateMahasiswa = new javax.swing.JButton();
        deleteMahasiswa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        halamanRuangan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Kode = new javax.swing.JTextField();
        Keterangan = new javax.swing.JTextField();
        tambahRuangan = new javax.swing.JButton();
        updateRuangan = new javax.swing.JButton();
        deleteRuangan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRuangan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        halamanBooking = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NIMBooking = new javax.swing.JTextField();
        NamaBooking = new javax.swing.JTextField();
        RuanganBooking = new javax.swing.JComboBox<>();
        startBooking = new javax.swing.JTextField();
        finishBooking = new javax.swing.JTextField();
        tambahBooking = new javax.swing.JButton();
        updateBooking = new javax.swing.JButton();
        deleteBooking = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMahasiswa = new javax.swing.JMenu();
        menuRuangan = new javax.swing.JMenu();
        menuPemesanan = new javax.swing.JMenu();

        jLabel7.setText("KODE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Discussion Room");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("MAHASISWA");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel4.setText("JURUSAN");

        tambahMahasiswa.setText("INSERT");
        tambahMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMahasiswaActionPerformed(evt);
            }
        });

        updateMahasiswa.setText("UPDATE");
        updateMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMahasiswaActionPerformed(evt);
            }
        });

        deleteMahasiswa.setText("DELETE");
        deleteMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMahasiswaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("DAFTAR MAHASISWA");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "colom", "NAMA", "JURUSAN"
            }
        ));
        tableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMahasiswa);

        jButton4.setText("logout");

        javax.swing.GroupLayout halamanMahasiswaLayout = new javax.swing.GroupLayout(halamanMahasiswa);
        halamanMahasiswa.setLayout(halamanMahasiswaLayout);
        halamanMahasiswaLayout.setHorizontalGroup(
            halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanMahasiswaLayout.createSequentialGroup()
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(halamanMahasiswaLayout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(halamanMahasiswaLayout.createSequentialGroup()
                        .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(halamanMahasiswaLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanMahasiswaLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(tambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jurusan)
                            .addComponent(Nama)
                            .addComponent(NIM)
                            .addGroup(halamanMahasiswaLayout.createSequentialGroup()
                                .addComponent(updateMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(deleteMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        halamanMahasiswaLayout.setVerticalGroup(
            halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(halamanMahasiswaLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NIM))
                .addGap(26, 26, 26)
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nama))
                .addGap(18, 18, 18)
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jurusan))
                .addGap(55, 55, 55)
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanMahasiswaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(halamanMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("RUANGAN");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel8.setText("KODE");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel9.setText("KETERANGAN");

        tambahRuangan.setText("INSERT");
        tambahRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahRuanganActionPerformed(evt);
            }
        });

        updateRuangan.setText("UPDATE");
        updateRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRuanganActionPerformed(evt);
            }
        });

        deleteRuangan.setText("DELETE");
        deleteRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRuanganActionPerformed(evt);
            }
        });

        tableRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode", "Keterangan"
            }
        ));
        tableRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRuanganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableRuangan);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("DAFTAR RUANGAN");

        javax.swing.GroupLayout halamanRuanganLayout = new javax.swing.GroupLayout(halamanRuangan);
        halamanRuangan.setLayout(halamanRuanganLayout);
        halamanRuanganLayout.setHorizontalGroup(
            halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(halamanRuanganLayout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanRuanganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanRuanganLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(tambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(halamanRuanganLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Kode)
                            .addComponent(Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(halamanRuanganLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(updateRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        halamanRuanganLayout.setVerticalGroup(
            halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(halamanRuanganLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(halamanRuanganLayout.createSequentialGroup()
                        .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(halamanRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setText("BOOKING");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel12.setText("NIM");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel13.setText("NAMA");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel14.setText("RUANGAN");

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel15.setText("START");

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel16.setText("FINISH");

        NIMBooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NIMBookingFocusLost(evt);
            }
        });

        NamaBooking.setEditable(false);

        startBooking.setText("00:00");
        startBooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                startBookingFocusLost(evt);
            }
        });

        finishBooking.setEditable(false);

        tambahBooking.setText("INSERT");
        tambahBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBookingActionPerformed(evt);
            }
        });

        updateBooking.setText("UPDATE");
        updateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookingActionPerformed(evt);
            }
        });

        deleteBooking.setText("DELETE");
        deleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setText("DAFTAR PEMESANAN");

        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Ruangan", "NIM", "Start", "Finish"
            }
        ));
        tableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookingMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBooking);

        javax.swing.GroupLayout halamanBookingLayout = new javax.swing.GroupLayout(halamanBooking);
        halamanBooking.setLayout(halamanBookingLayout);
        halamanBookingLayout.setHorizontalGroup(
            halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(halamanBookingLayout.createSequentialGroup()
                .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(halamanBookingLayout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jLabel11))
                    .addGroup(halamanBookingLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(tambahBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NIMBooking)
                                .addComponent(NamaBooking)
                                .addComponent(RuanganBooking, 0, 218, Short.MAX_VALUE)
                                .addComponent(startBooking)
                                .addComponent(finishBooking))
                            .addGroup(halamanBookingLayout.createSequentialGroup()
                                .addComponent(updateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(deleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, halamanBookingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(290, 290, 290))
        );
        halamanBookingLayout.setVerticalGroup(
            halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(halamanBookingLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(halamanBookingLayout.createSequentialGroup()
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NIMBooking)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaBooking)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RuanganBooking)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startBooking)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finishBooking))
                        .addGap(28, 28, 28)
                        .addGroup(halamanBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(tambahBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        menuMahasiswa.setText("Mahasiswa");
        menuMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMahasiswaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMahasiswa);

        menuRuangan.setText("Ruangan");
        menuRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRuanganMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRuangan);

        menuPemesanan.setText("Pemesanan");
        menuPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPemesananMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPemesanan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(halamanMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(halamanRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(halamanBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(halamanMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(halamanRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(halamanBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMahasiswaActionPerformed
        // TODO add your handling code here:
        modelMahasiswa model = new modelMahasiswa();
        model.tambahMahasiswa(NIM.getText(),Nama.getText(),Jurusan.getText());
        model.clearMahasiswaForm(NIM, Nama, Jurusan);
        model.refreshTable(tableMahasiswa, "mahasiswa");
    }//GEN-LAST:event_tambahMahasiswaActionPerformed

    private void updateMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMahasiswaActionPerformed
        // TODO add your handling code here:
        modelMahasiswa model = new modelMahasiswa();
        model.updateMahasiswa(NIM.getText(), Nama.getText(), Jurusan.getText());
        model.clearMahasiswaForm(NIM, Nama, Jurusan);
        model.refreshTable(tableMahasiswa, "mahasiswa");
    }//GEN-LAST:event_updateMahasiswaActionPerformed

    private void deleteMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMahasiswaActionPerformed
        // TODO add your handling code here:
        modelMahasiswa model = new modelMahasiswa();
        model.deleteMahasiswa(NIM.getText());
        model.clearMahasiswaForm(NIM, Nama, Jurusan);
        model.refreshTable(tableMahasiswa, "mahasiswa");
    }//GEN-LAST:event_deleteMahasiswaActionPerformed

    private void tableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMahasiswaMouseClicked
        // TODO add your handling code here:
        modelMahasiswa model = new modelMahasiswa();
        model.setMahasiswaForm(tableMahasiswa.getSelectedRow(), NIM, Nama, Jurusan, tableMahasiswa);
    }//GEN-LAST:event_tableMahasiswaMouseClicked

    private void tambahRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahRuanganActionPerformed
        // TODO add your handling code here:
        modelRuangan model = new modelRuangan();
        model.tambahRuangan(Kode.getText(),Keterangan.getText());
        model.clearRuanganForm(Kode, Keterangan);
        model.refreshTable(tableRuangan, "ruangan");
    }//GEN-LAST:event_tambahRuanganActionPerformed

    private void updateRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRuanganActionPerformed
        // TODO add your handling code here:
        modelRuangan model = new modelRuangan();
        model.updateRuangan(Kode.getText(),Keterangan.getText());
        model.clearRuanganForm(Kode, Keterangan);
        model.refreshTable(tableRuangan, "ruangan");
    }//GEN-LAST:event_updateRuanganActionPerformed

    private void deleteRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRuanganActionPerformed
        // TODO add your handling code here:
        modelRuangan model = new modelRuangan();
        model.deleteRuangan(Kode.getText());
        model.clearRuanganForm(Kode, Keterangan);
        model.refreshTable(tableRuangan, "ruangan");        
    }//GEN-LAST:event_deleteRuanganActionPerformed

    private void tableRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRuanganMouseClicked
        // TODO add your handling code here:        
        modelRuangan model = new modelRuangan();
        model.setRuanganForm(tableRuangan.getSelectedRow(), Kode, Keterangan, tableRuangan);
    }//GEN-LAST:event_tableRuanganMouseClicked

    private void NIMBookingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NIMBookingFocusLost
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.setNamaBooking(NIMBooking.getText(), NamaBooking);
    }//GEN-LAST:event_NIMBookingFocusLost

    private void startBookingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_startBookingFocusLost
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.setFinishBooking(startBooking.getText(), finishBooking);
    }//GEN-LAST:event_startBookingFocusLost

    private void tambahBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBookingActionPerformed
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.tambahBooking((String) RuanganBooking.getSelectedItem(), NIMBooking.getText(), startBooking.getText(), finishBooking.getText(), 
                            model.verifikasi(startBooking.getText(), finishBooking.getText(), (String) RuanganBooking.getSelectedItem()));
        model.clearBookingForm(NIMBooking, NamaBooking, RuanganBooking, startBooking, finishBooking);
        model.refreshTable(tableBooking);        
    }//GEN-LAST:event_tambahBookingActionPerformed

    private void updateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookingActionPerformed
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.updateBooking((String) RuanganBooking.getSelectedItem(), NIMBooking.getText(), startBooking.getText(), finishBooking.getText(), 
                            model.verifikasi(startBooking.getText(), finishBooking.getText(), (String) RuanganBooking.getSelectedItem()));
        model.clearBookingForm(NIMBooking, NamaBooking, RuanganBooking, startBooking, finishBooking);
        model.refreshTable(tableBooking); 
    }//GEN-LAST:event_updateBookingActionPerformed

    private void deleteBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingActionPerformed
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.deleteBooking();
        model.clearBookingForm(NIMBooking, NamaBooking, RuanganBooking, startBooking, finishBooking);
        model.refreshTable(tableBooking);
    }//GEN-LAST:event_deleteBookingActionPerformed

    private void tableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookingMouseClicked
        // TODO add your handling code here:
        modelBooking model = new modelBooking();
        model.setBookingnForm(tableBooking.getSelectedRow(), NIMBooking, NamaBooking, RuanganBooking, startBooking, finishBooking, tableBooking);
    }//GEN-LAST:event_tableBookingMouseClicked

    private void menuMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMahasiswaMouseClicked
        // TODO add your handling code here:        
        modelMahasiswa model = new modelMahasiswa();
        modelMahasiswa.modelMahasiswa(menuMahasiswa, halamanMahasiswa, halamanRuangan, halamanBooking);
        model.refreshTable(tableMahasiswa, "mahasiswa");
    }//GEN-LAST:event_menuMahasiswaMouseClicked

    private void menuRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRuanganMouseClicked
        // TODO add your handling code here:        
        modelRuangan model = new modelRuangan();
        modelRuangan.modelRuangan(menuRuangan, halamanMahasiswa, halamanRuangan, halamanBooking);
        model.refreshTable(tableRuangan, "ruangan");
    }//GEN-LAST:event_menuRuanganMouseClicked

    private void menuPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPemesananMouseClicked
        // TODO add your handling code here:        
        modelBooking model = new modelBooking();
        modelBooking.modelBooking(menuPemesanan, halamanMahasiswa, halamanRuangan, halamanBooking);
        model.refreshTable(tableBooking);
    }//GEN-LAST:event_menuPemesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingDiscussionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingDiscussionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingDiscussionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingDiscussionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingDiscussionRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Jurusan;
    public javax.swing.JTextField Keterangan;
    public javax.swing.JTextField Kode;
    public javax.swing.JTextField NIM;
    public javax.swing.JTextField NIMBooking;
    public javax.swing.JTextField Nama;
    public javax.swing.JTextField NamaBooking;
    public javax.swing.JComboBox<String> RuanganBooking;
    public javax.swing.JButton deleteBooking;
    private javax.swing.JButton deleteMahasiswa;
    public javax.swing.JButton deleteRuangan;
    public javax.swing.JTextField finishBooking;
    public javax.swing.JPanel halamanBooking;
    public javax.swing.JPanel halamanMahasiswa;
    public javax.swing.JPanel halamanRuangan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JMenu menuMahasiswa;
    public javax.swing.JMenu menuPemesanan;
    public javax.swing.JMenu menuRuangan;
    public javax.swing.JTextField startBooking;
    public javax.swing.JTable tableBooking;
    public javax.swing.JTable tableMahasiswa;
    public javax.swing.JTable tableRuangan;
    public javax.swing.JButton tambahBooking;
    private javax.swing.JButton tambahMahasiswa;
    public javax.swing.JButton tambahRuangan;
    public javax.swing.JButton updateBooking;
    private javax.swing.JButton updateMahasiswa;
    public javax.swing.JButton updateRuangan;
    // End of variables declaration//GEN-END:variables
}
